[package]
name = "shalom_dart"
version = "0.1.0"
edition = "2024"

[dependencies]
shalom_core = { path = "../shalom_core" }
shalom_runtime = { path = "../shalom_runtime" }
serde = {workspace = true}
serde_json = {workspace = true}
tokio = "1.48.0"
anyhow = {workspace = true}
